/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dragon: typeof import('./src/components/dragon.vue')['default']
    Phase1: typeof import('./src/components/Phase1.vue')['default']
    ProgressiveImage: typeof import('./src/components/ProgressiveImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
